export const teamMembers = [
  {
    id: 1,
    name: "Ranveer",
    role: "Frontend Developer",
    bio: "Specializes in React, Vue.js, and modern UI/UX design principles.",
    skills: ["React", "JavaScript", "CSS"],
    roleSlug: "frontend",
  },
  {
    id: 2,
    name: "Sudhanshu",
    role: "Backend Developer",
    bio: "Expert in Node.js, Python, and database architecture.",
    skills: ["Node.js", "Python", "MongoDB"],
    roleSlug: "backend",
  },
  {
    id: 3,
    name: "Jaspreet",
    role: "Full Stack Developer",
    bio: "Proficient in MERN stack and cloud deployment solutions.",
    skills: ["MERN", "AWS", "Docker"],
    roleSlug: "fullstack",
  },
  {
    id: 4,
    name: "Arshdeep",
    role: "UI/UX Designer",
    bio: "Creates beautiful and intuitive user experiences with Figma and Adobe XD.",
    skills: ["Figma", "Adobe XD", "Sketch"],
    roleSlug: "uiux",
  },
  {
    id: 5,
    name: "Sunidhi",
    role: "DevOps Engineer",
    bio: "Manages CI/CD pipelines and infrastructure automation.",
    skills: ["Kubernetes", "Jenkins", "Terraform"],
    roleSlug: "devops",
  },
  {
    id: 6,
    name: "Suraj",
    role: "Mobile Developer",
    bio: "Builds native and cross-platform mobile applications.",
    skills: ["React Native", "Flutter", "Swift"],
    roleSlug: "mobile",
  },
];